server:
  port: 8079
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
        default-filters:
          - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:

        # M1: tarifas-service (Controlador en /tarifas)
        - id: M1-tarifas-service
          uri: lb://tarifa-service
          predicates:
            - Path=/tarifa/**

        # M2: descuentos-grupo-service (Controlador en /descuentos-grupo)
        - id: M2-descuentos-grupo-service
          uri: lb://grupo-descuento-service
          predicates:
            - Path=/descuentoGrupo/**

        # M3: descuentos-frecuentes-service (Controlador en /descuentos-frecuentes)
        - id: M3-descuentos-frecuentes-service
          uri: lb://cliente-frecuente-service
          predicates:
            - Path=/clienteFrecuente/**

        # M4: tarifas-especiales-service (Controlador en /tarifas-especiales)
        - id: M4-tarifas-especiales-service
          uri: lb://dia-especial-service
          predicates:
            - Path=/tarifaEspecial/**

        # M5: reservas-comprobantes-service (Controlador Reserva en /reservas)
        - id: M5-reservas-service # Un id específico para las rutas de reservas
          uri: lb://reserva-service
          predicates:
            - Path=/reserva/**

        # M5: reservas-comprobantes-service (Controlador Comprobante en /comprobantes)
        - id: M5-comprobantes-service # Un id específico para las rutas de comprobantes
          uri: lb://reserva-service
          predicates:
            - Path=/comprobante/**

        # M6: rack-pista-service (Controlador en /rack)
        #- id: M6-rack-pista-service
        #  uri: lb://rack-pista-service
        #  predicates:
        #    - Path=/rack/**

        # M7: reportes-service (Controlador en /reportes)
        - id: M7-reportes-service
          uri: lb://reporte-service
          predicates:
            - Path=/reporte/**