server:
  port: 0
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/M5
    username: postgres
    password: forojuegos
  mail:
    host: smtp.gmail.com
    port: 587
    username: ignacio.celis@usach.cl
    password: xdag vdwx nwhn lsqu
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/