server:
  port: 0
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL_M5}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: forojuegos
  mail:
    host: smtp.gmail.com
    port: 587
    username: ignacio.celis@usach.cl
    password: xdag vdwx nwhn lsqu
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
eureka:
  instance:
    preferIpAddress: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server-service:8761/eureka/