apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-deployment
  labels:
    app: api-gateway-deployment
spec:
  selector:
    matchLabels:
      app: api-gateway-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: api-gateway-deployment
    spec:
      containers:
        - name: api-gateway
          image: ignaciocelis2003/api-gateway:latest
          ports:
            - containerPort: 8079
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
  labels:
    app: api-gateway-service
spec:
  selector:
    app: api-gateway-deployment
  ports:
    - protocol: TCP
      port: 8079
      targetPort: 8079
  type: LoadBalancer