apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-server-deployment
  labels:
    app: discovery-server-deployment
spec:
  selector:
    matchLabels:
      app: discovery-server-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: discovery-server-deployment
    spec:
      containers:
        - name: discovery-server
          image: ignaciocelis2003/discovery-server:latest
          ports:
            - containerPort: 8761
---
apiVersion: v1
kind: Service
metadata:
  name: discovery-server-service
  labels:
    app: discovery-server-service
spec:
  selector:
    app: discovery-server-deployment
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761
  type: LoadBalancer